config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'persons#new'
  post '/', to: 'persons#create'

  get '/admins/dashboard', to: 'admins/dashboard#index'
  get '/admins/dashboard/:person_id/:phase_id', to: 'admins/dashboard/user_phases#show'
  get '/admins/pending_admins', to: 'admins/pending#index'

  get '/admins/login', to: 'admins_sessions#new'
  post '/admins/login', to: 'admins_sessions#create'
  delete '/logout', to: 'admins_sessions#destroy'

  resources :admins, only: [:new, :create]

  get '/:person_id/results', to: 'phases#create'
  get '/:person_id/results/:id', to: 'phases#show'
end

app/controllers/admins_sessions_controller.rb
 class AdminsSessionsController < ApplicationController 

    def new
    end 

    def create 
        admin = Admin.find_by(username: params[:username])
        if admin&.authenticate(params[:password])
            session[:admin_id] = admin.id 
            redirect_to "/admins/dashboard" 
            flash[:success] = "Welcome, #{admin.username}"
        else 
            flash[:error] = "Sorry, your credentials are bad"
            render :new
        end 
    end 

    def destroy 
        session.destroy
        redirect_to '/admins/login'
    end 
end 

app/views/admins_sessions/new.html.erb
<% if current_admin %>
    <p>You're logged in </p>
    <%= link_to "Logout", '/logout', method: :delete %>
    <%= link_to "Dashboard", '/admins/dashboard' %>
<% else %>
    <%= link_to "Register as an admin", new_admin_path %>
<% end %>

<%= form_with url: "/admins/login", local: true do |form|%>
    <%= form.label :username %>
    <%= form.text_field :username, required: true %>
    <br>
    <%= form.label :password %>
    <%= form.text_field :password, required: true %>
    <br>
    <%= form.submit "Login" %>
<% end %>